#!/bin/sh

set -e

echo 'Installing dependencies...'
bundle install

if [ ! -f config/application.yml ]; then
  echo 'Setting default environment variables...'
  cp config/application.example.yml config/application.yml
fi

echo 'All done!'
